apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-app
  namespace: argocd
spec:
  project: default
  # this sync policy will deploy the app without confirmation when changes are detected
  syncPolicy:
    automated: {}
  source:
    repoURL: https://github.com/vmware-tanzu/carvel-simple-app-on-kubernetes.git
    targetRevision: develop
    path: config-step-1-minimal

  destination:
    server: https://kubernetes.default.svc
