envName: appofapps

#projectOverride: default

default:
  project:
    destinations: |
      - namespace: {{ $.Values.default.app.destination.namespace | required "Missing proj dest namespace"}}
        server: {{ $.Values.default.app.destination.server | required "Missing proj dest server" }}
  app:
    enableAutoSync: true
    autoSyncPrune: true
    destination:
      namespace: null
      server: https://kubernetes.default.svc
    project: null
    source:
      path: null
      repoURL: null
      targetRevision: HEAD

projects:
  servers:
    description: 'nginx servers'
    sourceRepos:
      -  https://github.com/kubernetes/ingress-nginx/*

applications:
  nginx1:
    enabled: true
    destination:
      namespace: default
      server: null
    project: servers
    source:
      path: ./charts/ingress-nginx
      repoURL: https://github.com/kubernetes/ingress-nginx.git
      targetRevision: HEAD

  nginx2:
    enabled: true
    destination:
      namespace: default
      server: null
    project: servers
    source:
      path: ./charts/ingress-nginx
      repoURL: https://github.com/kubernetes/ingress-nginx.git
      targetRevision: HEAD
