envName: appofapps

projectOverride: default

default:
  app:
    enableAutoSync: true
    autoSyncPrune: true
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    project: null
    source:
      path: null
      repoURL: null
      targetRevision: null

applications:
  nginx1:
    enabled: true
    destination:
      namespace: null
      server: null
    project: null
    source:
      path: ./charts/ingress-nginx
      repoURL: https://github.com/kubernetes/ingress-nginx.git
      targetRevision: HEAD

  nginx2:
    enabled: true
    destination:
      namespace: null
      server: null
    project: null
    source:
      path: ./charts/ingress-nginx
      repoURL: https://github.com/kubernetes/ingress-nginx.git
      targetRevision: HEAD
